# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/Arch Labs/Exp6/code/constraint.xdc

# IP: ip/multiplier/multiplier.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==multiplier || ORIG_REF_NAME==multiplier} -quiet] -quiet
